services:
  api:
    depends_on:
      - mssql
    build: .
    ports:
      - "5122:80"
      - "7122:443"
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    hostname: mssql
    restart: always
    environment:
      - SA_PASSWORD=${DB_PASS}
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"